# -*- coding: utf-8 -*-
"""entregable1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nick9vsI-eJB3eMmdeVzvFDFG0vi8qI0
"""

pip install requests

import requests

import time

frases=requests.get("https://thesimpsonsquoteapi.glitch.me/quotes"
)

print(frases.status_code)

print(frases.json())

print(frases.json()[0]["quote"])

def tiempoPeticion():
  for i in range(20):
    frases=requests.get("https://thesimpsonsquoteapi.glitch.me/quotes"
)
    print(frases.json()[0]["quote"])
    print(frases.json()[0]["character"])
    print(frases.json()[0]["image"])
    time.sleep(30)

tiempoPeticion()



