FROM python:3.9.7
RUN apt-get update

COPY /entregable1.py /app/
COPY /requierments.txt /app/
RUN mkdir "Lisa Simpson"
RUN mkdir "Homer Simpson"

RUN pip-install -p requierments.txt

CMD [ "python" , "entregable1.py"]
