FROM python:3.9.7
RUN apt-get update

COPY entregable1.py /app
COPY requirements.txt /app


RUN mkdir "Lisa Simpson"
RUN mkdir "Homer Simpson"

RUN pip freeze > requirements.txt
RUN pip install -r requirements.txt

CMD [ "python3" , "entregable1.py"]
