# -*- coding: utf-8 -*-
"""entregable1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nick9vsI-eJB3eMmdeVzvFDFG0vi8qI0
"""


import requests
import time
import csv
from csv import writer
from csv import DictWriter

#frases=requests.get("https://thesimpsonsquoteapi.glitch.me/quotes"


#print(frases.status_code)

#print(frases.json())

#print(frases.json()[0]["quote"])

def tiempoPeticion():
  for i in range(20):
    frases=requests.get("https://thesimpsonsquoteapi.glitch.me/quotes"
)
    texto=frases.json()[0]["quote"]
    personaje=frases.json()[0]["character"]
    imagen=frases.json()[0]["image"]
    print(texto)
    print(personaje)
    print(imagen)
    time.sleep(10)

    data={"quote":texto,"character":personaje,"image":imagen}
    if personaje == 'Homer Simpson':
        with open('HOMER/mycsvfile.csv', 'a', newline='') as f: 
            a=csv.DictWriter(f,data.keys())
            a.writerow(data)
    elif personaje == 'Lisa Simpson':
         with open('LISA/mycsvfile.csv', 'a', newline='') as g: 
            a=csv.DictWriter(g,data.keys())
            a.writerow(data)
    else:
        with open('GENERAL/mycsvfile.csv', 'a', newline='') as h: 
            a=csv.DictWriter(h,data.keys())
            a.writerow(data)
    
tiempoPeticion()



